#index:
#    path: /
#    controller: App\Controller\DefaultController::index
predict:
  path: /predict
  controller: App\Controller\PredictionController::predict

index2:
  path: /predictEnvironement
  controller: App\Controller\PredictionController::index2