<?php

namespace ContainerQpHy5St;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlaskIntegrationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FlaskIntegrationService' shared autowired service.
     *
     * @return \App\Service\FlaskIntegrationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FlaskIntegrationService.php';

        return $container->privates['App\\Service\\FlaskIntegrationService'] = new \App\Service\FlaskIntegrationService('http://127.0.0.1:5000');
    }
}
