<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3olFxOi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3olFxOi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3olFxOi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3olFxOi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3olFxOi\App_KernelDevDebugContainer([
    'container.build_hash' => '3olFxOi',
    'container.build_id' => '4f037b90',
    'container.build_time' => 1683134252,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3olFxOi');
