<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxOdQ40\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxOdQ40/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxOdQ40.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxOdQ40\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxOdQ40\App_KernelDevDebugContainer([
    'container.build_hash' => 'UxOdQ40',
    'container.build_id' => '408e6b79',
    'container.build_time' => 1683480211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxOdQ40');
