<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQpHy5St\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQpHy5St/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQpHy5St.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQpHy5St\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQpHy5St\App_KernelDevDebugContainer([
    'container.build_hash' => 'QpHy5St',
    'container.build_id' => '733437f3',
    'container.build_time' => 1683925912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQpHy5St');
